### ISSUE TITLE
Doesn't work on next.js

### ISSUE THREAD

**Issue by mohammadraasel** [GeoffCox/react-splitter#20]
`ReferenceError: window is not defined`

This error happened while generating the page

**Comment by GeoffCox** [comment]
I will need more information before I could have a fix or update.  Generally, in next.js when this error occurs it is because of a server-side rendering issue.  The react-splitter code does not directly use window.  I haven't done anything to avoid supporting SSR, but haven't tested this component on it.

**Comment by n-hallberg** [comment]
Would be cool! Dropped it today after a whole while of fiddeling with dynamic import in Next js.
The error was: "self is not defined".

Maybe the issue could be reopened?

**Comment by lsegal** [comment]
Seeing this as well. Would you accept a PR that fixes it?
